apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_USER: dXNlcg==        # base64 encoded "user"
  DB_PASSWORD: cGFzc3dvcmQ= # base64 encoded "password"
  DB_NAME: bXlkYg==        # base64 encoded "mydb"
